# permissions for end users to view etcdclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcdcluster-viewer-role
rules:
- apiGroups:
  - etcd.ydzs.io
  resources:
  - etcdclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - etcd.ydzs.io
  resources:
  - etcdclusters/status
  verbs:
  - get
